url: http://localhost:4000/
baseurl: ''

# Site Settings
title: Portafolio
description: "Timeline is multipurpose, single page Jekyll theme that includes a timeline section."
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
